/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pepa;

import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gabriel
 */
public class AAInterfaz extends javax.swing.JFrame {
    public static boolean EnProceso = false;
    public static int numeroID = 00000;
    public static Cola Prioridad1 = new Cola();
    public static Cola Prioridad2 = new Cola();
    public static Cola Prioridad3 = new Cola();
    public static Semaphore tlfenfabrica = new Semaphore(20);
    /**
     * Creates new form AAInterfaz
     */
    public AAInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cola3fab1 = new javax.swing.JLabel();
        Cola2fab1 = new javax.swing.JLabel();
        Cola1fab1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Comenzar = new javax.swing.JToggleButton();
        Cantidadcola1 = new javax.swing.JLabel();
        Cantidadcola3 = new javax.swing.JLabel();
        Cantidadcola2 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        Cola1fab2 = new javax.swing.JLabel();
        cola2fab2 = new javax.swing.JLabel();
        cola3fab2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cantidad2cola3 = new javax.swing.JLabel();
        Cantidad2cola1 = new javax.swing.JLabel();
        Cantidad2cola2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Colas");
        ventana.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 32, 24));

        Cola3fab1.setText("#3");
        ventana.add(Cola3fab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 32, 24));

        Cola2fab1.setText("#2");
        ventana.add(Cola2fab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 32, 24));

        Cola1fab1.setText("#1");
        ventana.add(Cola1fab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 32, 24));

        jLabel1.setText("Fabrica1");
        ventana.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 37));

        Comenzar.setText("Comenzar proceso");
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });
        ventana.add(Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        Cantidadcola1.setText("0");
        ventana.add(Cantidadcola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 30, 20));

        Cantidadcola3.setText("0");
        ventana.add(Cantidadcola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 30, 20));

        Cantidadcola2.setText("0");
        ventana.add(Cantidadcola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 30, 20));

        jToggleButton2.setText("Parar Proceso");
        ventana.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel3.setText("Colas");
        ventana.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 32, 24));

        Cola1fab2.setText("#1");
        ventana.add(Cola1fab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 32, 24));

        cola2fab2.setText("#2");
        ventana.add(cola2fab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 32, 24));

        cola3fab2.setText("#3");
        ventana.add(cola3fab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 32, 24));

        jLabel4.setText("Fabrica2");
        ventana.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 37));

        Cantidad2cola3.setText("0");
        ventana.add(Cantidad2cola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 30, 20));

        Cantidad2cola1.setText("0");
        ventana.add(Cantidad2cola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 30, 20));

        Cantidad2cola2.setText("0");
        ventana.add(Cantidad2cola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 30, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventana, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed
        CreadorTlf hilotlfs = new CreadorTlf();
        hilotlfs.start();

    }//GEN-LAST:event_ComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AAInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AAInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AAInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AAInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AAInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Cantidad2cola1;
    public static javax.swing.JLabel Cantidad2cola2;
    public static javax.swing.JLabel Cantidad2cola3;
    public static javax.swing.JLabel Cantidadcola1;
    public static javax.swing.JLabel Cantidadcola2;
    public static javax.swing.JLabel Cantidadcola3;
    private javax.swing.JLabel Cola1fab1;
    private javax.swing.JLabel Cola1fab2;
    private javax.swing.JLabel Cola2fab1;
    private javax.swing.JLabel Cola3fab1;
    private javax.swing.JToggleButton Comenzar;
    private javax.swing.JLabel cola2fab2;
    private javax.swing.JLabel cola3fab2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}
